import type { Metadata } from "next";
import { Parkinsans } from "next/font/google";
import localFont from 'next/font/local';
import "./globals.css";

const parkinsans = Parkinsans({
  weight: ['400', '500', '600', '700'],
  subsets: ["latin"],
  variable: "--font-parkinsans",
  adjustFontFallback: false
});

const mina = localFont({
  src: [
    {
      path: '../public/fonts/Mina-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/Mina-Bold.ttf',
      weight: '700',
      style: 'normal',
    }
  ],
  variable: '--font-mina',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${parkinsans.variable} ${mina.variable} min-h-screen bg-background text-foreground`}>
        {children}
      </body>
    </html>
  );
}
